version: '3'
services:
  db:
    image: postgres:13.1
    container_name: learn-postgres-13.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - db.env
    command: postgres
    volumes:
      - ./dbdata/:/var/lib/postgresql/data
      - ./dump/:/dump/
